services:
  postgresdb:
    image: postgres:15
    container_name: emailBD
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emailDB
    ports:
      - "5434:5432"
    volumes:
      - userproj_postgres_data:/var/lib/postgresql/data

volumes:
  userproj_postgres_data:



